# VARIALBES
from sklearn import linear_model
from sklearn import svm
from key import *
MOVIENAME = 'Mad Max Fury Road'

departments = [
    'Sound',
    'Camera',
    'Costume & Make-Up',
    'Crew',
    'Directing',
    'Writing',
    'Visual Effects',
    'Production',
    'Art',
    'Editing']
genres = [
    'Action',
    'Adventure',
    'Animation',
    'Comedy',
    'Crime',
    'Documentary',
    'Drama',
    'Family',
    'Fantasy',
    'Foreign',
    'History',
    'Horror',
    'Music',
    'Mystery',
    'Romance',
    'Science Fiction',
    'TV movie',
    'Thriller',
    'War',
    'Western']
productionCompaniesPopluate = []
genreTest = []
movieNameList = [
    u"Who's Your Caddy?\n",
    u'Son of the Mask\n',
    u'Troll 2\n',
    u'Gigli\n',
    u'BloodRayne\n',
    u'You Got Served\n',
    u'Barb Wire\n',
    u'Catwoman\n',
    u'Superman IV: The Quest for Peace\n',
    u'Batman & Robin\n',
    u'Police Academy 5: Assignment: Miami Beach\n',
    u'The Wicker Man\n',
    u'Dungeons & Dragons\n',
    u'In the Name of the King: A Dungeon Siege Tale\n',
    u'Bio-Dome\n',
    u'Basic Instinct 2\n',
    u'On Deadly Ground\n',
    u'Halloween III: Season of the Witch\n',
    u'The Adventures of Rocky & Bullwinkle\n',
    u'The Karate Kid, Part III\n',
    u'The Last Airbender\n',
    u'Skyline\n',
    u"Freddy's Dead: The Final Nightmare\n",
    u'Dr. Dolittle 2\n',
    u'Jonah Hex\n',
    u'Envy\n',
    u'Miss Congeniality 2: Armed & Fabulous\n',
    u'Flubber\n',
    u"Charlie's Angels: Full Throttle\n",
    u'The Covenant\n',
    u'The Haunted Mansion\n',
    u'Cold Creek Manor\n',
    u'Queen of the Damned\n',
    u'Elektra\n',
    u'The Dukes of Hazzard\n',
    u'Shutter\n',
    u'An American Haunting\n',
    u'An American Werewolf in Paris\n',
    u'The Specialist\n',
    u'Little Nicky\n',
    u'Masters of the Universe\n',
    u'Star Trek V: The Final Frontier\n',
    u'Beverly Hills Cop III\n',
    u'Raw Deal\n',
    u'The Tuxedo\n',
    u'Scary Movie 4\n',
    u'Johnny Mnemonic\n',
    u'The Hills Have Eyes II\n',
    u'Loser\n',
    u'Agent Cody Banks\n',
    u'Pathfinder\n',
    u'Beethoven\n',
    u'Collateral Damage\n',
    u'Urban Legend\n',
    u'American Pie Presents Beta House\n',
    u'Dracula: Dead and Loving It\n',
    u'The Ten\n',
    u'Children of the Corn\n',
    u'Hollywood Homicide\n',
    u'Bulletproof Monk\n',
    u'The Pacifier\n',
    u'Volcano\n',
    u'Forces of Nature\n',
    u'The Bonfire of the Vanities\n',
    u'Virtuosity\n',
    u'Timeline\n',
    u'Little Fockers\n',
    u'Ghost Ship\n',
    u'Paul Blart: Mall Cop\n',
    u'The Skulls\n',
    u'Kicking & Screaming\n',
    u'Drumline\n',
    u'AVP: Alien vs. Predator\n',
    u'White Noise\n',
    u'I Know What You Did Last Summer\n',
    u'Conan the Destroyer\n',
    u'Alvin and the Chipmunks\n',
    u'Bubble Boy\n',
    u'12 Rounds\n',
    u'John Tucker Must Die\n',
    u"Charlie's Angels\n",
    u'Nine 1/2 Weeks\n',
    u'Made of Honor\n',
    u'Perfect Stranger\n',
    u'The Art of War\n',
    u'Passenger 57\n',
    u'Turner & Hooch\n',
    u'Wrong Turn 2: Dead End\n',
    u'Analyze That\n',
    u'The Postman\n',
    u'Mr. Deeds\n',
    u'Men in Black II\n',
    u'Bridget Jones: The Edge of Reason\n',
    u'Space Jam\n',
    u'Jaws 2\n',
    u'Universal Soldier\n',
    u'The Legend of Zorro\n',
    u'Jurassic Park III\n',
    u'1941\n',
    u'Into the Blue\n',
    u'Win a Date with Tad Hamilton!\n',
    u'Mercury Rising\n',
    u'Johnny English\n',
    u'The Amityville Horror\n',
    u'The 6th Day\n',
    u'A Night at the Roxbury\n',
    u'Sweet Home Alabama\n',
    u'Waterworld\n',
    u'Chicken Little\n',
    u'Multiplicity\n',
    u'Georgia Rule\n',
    u'Black Sheep\n',
    u'Stick It\n',
    u'Reign of Fire\n',
    u'Murder by Numbers\n',
    u'The Replacement Killers\n',
    u"The Devil's Own\n",
    u'Addicted to Love\n',
    u'Bring It On\n',
    u'The Money Pit\n',
    u'Disclosure\n',
    u'The Cable Guy\n',
    u'Diary of the Dead\n',
    u'Dear John\n',
    u'Sahara\n',
    u'The Brothers Grimm\n',
    u'Thick as Thieves\n',
    u'Tango & Cash\n',
    u'Clash of the Titans\n',
    u'Walking Tall\n',
    u'Scary Movie\n',
    u'Green Card\n',
    u'The Invasion\n',
    u'The Ruins\n',
    u'Forever Young\n',
    u'Nine\n',
    u"All the King's Men\n",
    u'Die Another Day\n',
    u'The Dead Pool\n',
    u'Dinner for Schmucks\n',
    u'Piranha\n',
    u'Two for the Money\n',
    u'Cannibal Holocaust\n',
    u'War\n',
    u'Inkheart\n',
    u'Armageddon\n',
    u"One Night at McCool's\n",
    u'Punisher: War Zone\n',
    u'Big Daddy\n',
    u'The Nanny Diaries\n',
    u'Entrapment\n',
    u'Shrek the Third\n',
    u'American Wedding\n',
    u"Ocean's Twelve\n",
    u'The Adventures of Buckaroo Banzai Across the 8th Dimension\n',
    u'The Texas Chainsaw Massacre\n',
    u'Planet 51\n',
    u'*batteries not included\n',
    u'I Now Pronounce You Chuck & Larry\n',
    u'Starsky & Hutch\n',
    u'Beverly Hills Cop II\n',
    u'The Rocketeer\n',
    u'Once Upon a Time in Mexico\n',
    u'So I Married an Axe Murderer\n',
    u'Barbershop\n',
    u'Instinct\n',
    u'Kate & Leopold\n',
    u"Mr. Magorium's Wonder Emporium\n",
    u'Now and Then\n',
    u'Sydney White\n',
    u'The River Wild\n',
    u'The Siege\n',
    u'Tin Cup\n',
    u'Arachnophobia\n',
    u'The 51st State\n',
    u'Always\n',
    u'The Perfect Storm\n',
    u'Heartbreakers\n',
    u'Solomon Kane\n',
    u'Life as We Know It\n',
    u'Crash\n',
    u'The Ice Harvest\n',
    u'The Replacements\n',
    u'Lions for Lambs']
fingerPrint = []
clf = linear_model.LogisticRegression()


